import "../app/styles/globals.css"
import { ReactQueryClientProvider } from "./lib/query-provider";
import ThemeProvider from "./ThemeProvider";

export const metadata = {
  title: "Acsid Maad",
  description: "Generated by create next app",
  icons: {
    icon: "images/favicon.png"
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="" lang="en">
      <body className="bg-white dark:bg-zinc-900">
        <ReactQueryClientProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
